### ISSUE TITLE
Not able to build the project

### ISSUE THREAD

**Issue by jsphkhan** [dzannotti/react-thesidebar#2]
Hi,

I am not able to build the project. Getting some build issue in XCode. Please help. 
I did npm install to install the dependencies. 

![screen shot 2015-03-31 at 11 36 56 pm](https://cloud.githubusercontent.com/assets/1991609/6925729/121e93ce-d7ff-11e4-8c96-da7c9720a026.png)

Thanks.
Joseph

**Comment by dzannotti** [comment]
Hi Joseph, by the  looks of things you have an outdated xcode/iOS sdk which might create some problems with the compilation?
Looks like RCTViewManager.h is not in your path, and should be when compiling react native code

**Comment by jsphkhan** [comment]
Thanks. I will give it a try. Hope it works. 
Regards.
Joseph

**Comment by jsphkhan** [comment]
Seems to work now. React packager is unpredictable. Without any changes it started working today morning.

Thanks.
Joseph

**Comment by dzannotti** [comment]
No problem
