### ISSUE TITLE
Documentation on how to implement to an existing project

### ISSUE THREAD

**Issue by wski** [dzannotti/react-thesidebar#4]
This looks really awesome, Could you include some documentation on how we can include this in a existing project?

**Comment by developerworks** [comment]
+1

**Comment by dzannotti** [comment]
Sorry i'm not sure i understand what you need exactly? There's an example code in the readme.md and an example app distributed with this. Should be enough to get you started, if you can be more specific i can help you more.

**Comment by wski** [comment]
For those of us that are used to Node and React vs ObjectiveC Xcode and the rest it can be difficult for us to understand how to include this module. We are used to using NPM to install a module then simply requiring it and being on our way. At the time of opening this ticket that did not appear to be possible and I was unable to implement it into my current app



—
Matt Wisniewski
Software Engineer


A software engineer with a love for the web, JavaScript, and bold coffee overpowered by cheap creamer.




http://wski.github.io

http://github.com/wski

**Comment by dzannotti** [comment]
Unfortunately there's no clean way to distribute js+objc code in the same package yet :(
Will update the readme with a bit more description on how to integrate it tho!
