### ISSUE TITLE
Not on react.parts

### ISSUE THREAD

**Issue by brentvatne** [dzannotti/react-thesidebar#5]
You can get it on there using these steps: https://github.com/madebyform/react-parts#adding-a-new-component-to-the-catalog

:smile:

**Comment by brentvatne** [comment]
@dzannotti - any interest in pursuing this?

**Comment by dzannotti** [comment]
Hey, yes i can do, the only thing that i do wonder still is which way is the best to distribute this

**Comment by brentvatne** [comment]
@dzannotti - unfortunately this is still the best way: http://brentvatne.ca/packaging-react-native-component/
